// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJaEe9pakaDXJgoM9DIoT3amhbZ1NMdic',
    appId: '1:616446795152:web:4f6837fd57c2c5b4a9e715',
    messagingSenderId: '616446795152',
    projectId: 'foodly-f01f4',
    authDomain: 'foodly-f01f4.firebaseapp.com',
    storageBucket: 'foodly-f01f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiYPn2gmtLwspuF1tcVG2jbCCGsfbMzrk',
    appId: '1:616446795152:android:12f6882ec4e5b068a9e715',
    messagingSenderId: '616446795152',
    projectId: 'foodly-f01f4',
    storageBucket: 'foodly-f01f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-tMFMmDkrqyTH8KFbi5AkX6FzDh1ye7I',
    appId: '1:616446795152:ios:2d91dfffcb317496a9e715',
    messagingSenderId: '616446795152',
    projectId: 'foodly-f01f4',
    storageBucket: 'foodly-f01f4.firebasestorage.app',
    iosClientId: '616446795152-eaf95fdulkrrsdfivtq8utjuc5d73gfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiVendorApp',
  );
}
